### ISSUE TITLE
Hello, @banujan6 i have just seen your update but there is another problem, thing that you need patched

### ISSUE THREAD

**Issue by onebeat** [banujan6/CSRF-handler#12]
Hello, @banujan6 i have just seen your update but there is another problem, thing that you need patched

`private static function startSession()
		{
        if(!isset($_SESSION["X-CSRF-TOKEN-LIST"]) && session_status() == PHP_SESSION_NONE){
			session_start();
		}
	$_SESSION["X-CSRF-TOKEN-LIST"] = null; // initializing the index
}`

If somebody has session class on there own, without this it will show "notice" that session already started - also i have moved your $_SESSION["X-CSRF-TOKEN-LIST"]  out off IF loop :)

_Originally posted by @onebeat in https://github.com/banujan6/CSRF-handler/issues/7#issuecomment-625242126_

**Comment by banujan6** [comment]
**Thanks for you contribution!**
I have added patch on version@2.1.3.

By the way, Moving `$_SESSION["X-CSRF-TOKEN-LIST"] = null;` out of IF, May overwrite the session every time to NULL. Please avoid it.

I appreciate, If you could send PR to master repository :)
