### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by NonoMETAYER** [banujan6/CSRF-handler#15]
If you want to avoid loading the page a bit long

In the CSRF file you can annotate the code below:

Its keeps your script from looking for nothing.

```
//if (phpversion() < 5.5)
{
$hashedToken = hash('sha256', base64_encode($keySet.$userAgent.$clientIp));
}
/*else
{
$hashedToken = base64_encode(password_hash(base64_encode($keySet.$userAgent.$clientIp), PASSWORD_BCRYPT));
}*/
```

Thanks

**Comment by banujan6** [comment]
@NonoMETAYER  Thank you so much for your input. We no longer maintain this repository. We strongly recommend using frameworks that has built-in security mechanisms.
