### ISSUE TITLE
"Class 'csrf' not found"

### ISSUE THREAD

**Issue by emresaracoglu** [banujan6/CSRF-handler#16]
Hi @banujan6 ,

I added it with Composer but I get an error. What could be the reason for this?

> Error
> Class 'csrf' not found

```
use csrfhandler\csrf as csrf;
	$isValidCSRF = csrf::all();
```

PHP 7.3
Thank you.

**Comment by banujan6** [comment]
Hi, @emresaracoglu 
Did you import the library file or autoloader? 

Checkout https://github.com/banujan6/CSRF-handler page for code sample.

**Comment by emresaracoglu** [comment]
Hi,
Along with this project, I use it in different projects. Frankly, I tried it that day and when it failed, I didn't try again. I will try to install it again tomorrow. Thank you for your return.
