### ISSUE TITLE
Add checks for user agent and IP address

### ISSUE THREAD

**Issue by CodeAlDente** [banujan6/CSRF-handler#2]
To increase security there should be additional checks for user agent and IP address. Doing so a token is linked to the current browser and IP address which makes it more difficult to fake it and to use it in other application.

However, I do not recommend to save those information in plain text but rather would like to see them hashed for privacy reasons.

**Comment by banujan6** [comment]
@CodeAlDente Yes You are write. The current implementation is very basic. We are currently implementing user-agent, IP address & signature based authentication . Will release soon. 

Thank you for your support. And please get in touch with us for further projects
