### ISSUE TITLE
array_push() expects parameter 1 to be array, boolean given

### ISSUE THREAD

**Issue by mousel68** [banujan6/CSRF-handler#6]
I was getting this error in my source code:
array_push() expects parameter 1 to be array, boolean given in <b>csrf.php</b> on line <b>61

I changed:
			$tokenList = unserialize($_SESSION['X-CSRF-TOKEN-LIST']);

To this:
			$tokenList[] = unserialize($_SESSION['X-CSRF-TOKEN-LIST']);

And the error went away.

**Comment by banujan6** [comment]
@mousel68  Thank you! for reporting us,  Did you pull our last commit?

**Comment by banujan6** [comment]
@mousel68  Checkout v2.0.1
